name: antischool_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  firebase_core: ^2.31.0
  firebase_remote_config: ^4.4.5
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  gsheets: ^0.5.0
  responsive_sizer: ^3.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/